In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("../../datasets/Movie/movies_metadata.csv")
df.columns

C:\Users\chatl\AppData\Local\Temp\ipykernel_26704\2467241378.py:1: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../datasets/Movie/movies_metadata.csv")

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [20]:
df["original_language"].unique()

<StringArray>
[   'en',    'fr',    'zh',    'it',    'fa',    'nl',    'de',    'cn',
    'ar',    'es',    'ru',    'sv',    'ja',    'ko',    'sr',    'bn',
    'he',    'pt',    'wo',    'ro',    'hu',    'cy',    'vi',    'cs',
    'da',    'no',    'nb',    'pl',    'el',    'sh',    'xx',    'mk',
    'bo',    'ca',    'fi',    'th',    'sk',    'bs',    'hi',    'tr',
    'is',    'ps',    'ab',    'eo',    'ka',    'mn',    'bm',    'zu',
    'uk',    'af',    'la',    'et',    'ku',    'fy',    'lv',    'ta',
    'sl',    'tl',    'ur',    'rw',    'id',    'bg',    'mr',    'lt',
    'kk',    'ms',    'sq',     nan, '104.0',    'qu',    'te',    'am',
    'jv',    'tg',    'ml',    'hr',    'lo',    'ay',    'kn',    'eu',
    'ne',    'pa',    'ky',    'gl',  '68.0',    'uz',    'sm',    'mt',
  '82.0',    'hy',    'iu',    'lb',    'si']
Length: 93, dtype: str

In [21]:
english = df[df["original_language"]=='en']
french = df[df["original_language"]=='fr']

In [22]:
merged = pd.concat([english,french])

In [23]:
sorte = merged.sort_values(by='vote_average',ascending=False)

In [24]:
transposed = sorte.T

In [25]:
melted = pd.melt(
    df,
    id_vars=['genres'],
    value_vars=['revenue', 'runtime']
)

In [26]:
wide = melted.pivot_table(
    index=['genres'],
    columns='variable',
    values='value',
)

In [27]:
merged.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [28]:
sorte.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
29294,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,322460,tt0064192,en,Crooks and Coronets,Two crooks are hired to rob an eccentric old l...,...,1969-04-02,0.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The caper could get $5,000,000. All these Amer...",Crooks and Coronets,False,10.0,1.0
29276,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,72178,tt0091682,en,One Night Only,A group of female friends get together with so...,...,1986-01-06,0.0,87.0,[],Released,"What fantasy could be worth $50,000?",One Night Only,False,10.0,1.0
39760,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,86360,tt0020466,en,Sunnyside Up,"Molly and Bee, sweet young 'working girls,' li...",...,1929-12-25,0.0,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The screen's first original all talking, singi...",Sunnyside Up,False,10.0,1.0
42628,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",http://www.sho.com/titles/3432660/Sebastian%20...,415735,tt6295304,en,Sebastian Maniscalco: Why Would You Do That?,Comedian Sebastian Maniscalco performs his thi...,...,2016-10-01,0.0,63.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Sebastian Maniscalco: Why Would You Do That?,False,10.0,2.0
35343,False,NaN,300000,"[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...",NaN,140595,tt0308213,en,Elaine Stritch: At Liberty,Judy at the Palace. Sinatra at Carnegie Hall. ...,...,2002-01-01,0.0,140.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Legendary performances come along so rarely.,Elaine Stritch: At Liberty,False,10.0,1.0

In [29]:
transposed.head()

,29294,29276,39760,42628,35343,31251,22377,22255,45371,37119,...,27405,27465,20438,36155,107,164,27366,27474,19729,35586
adult,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
belongs_to_collection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'id': 477208, 'name': 'DC Super Hero Girls Co...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
budget,0,0,0,0,300000,60000,0,0,0,70000,...,0,0,0,0,0,0,0,0,0,0
genres,"[{'id': 35, 'name': 'Comedy'}]","[{'id': 35, 'name': 'Comedy'}]","[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 35, 'name': 'Comedy'}]","[{'id': 99, 'name': 'Documentary'}]","[{'id': 16, 'name': 'Animation'}]","[{'id': 18, 'name': 'Drama'}]",...,[],"[{'id': 9648, 'name': 'Mystery'}, {'id': 35, '...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",[],"[{'id': 80, 'name': 'Crime'}]","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 99, 'name': 'Documentary'}]","[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...","[{'id': 10770, 'name': 'TV Movie'}, {'id': 28,..."
homepage,NaN,NaN,NaN,http://www.sho.com/titles/3432660/Sebastian%20...,NaN,http://www.imdb.com/title/tt1274589/,http://oxenagos.gr/?page_id=186,NaN,NaN,http://www.shuttlecockboys.com/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
melted.head()

                                              genres variable        value
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  revenue  373554033.0
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  revenue  262797249.0
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  revenue          0.0
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  revenue   81452156.0
4                     [{'id': 35, 'name': 'Comedy'}]  revenue   76578911.0

In [31]:
wide.head()

variable                                                 revenue     runtime
genres
[]                                                  7.639705e+04   69.984349
[{'id': 10402, 'name': 'Music'}, {'id': 10749, ...  0.000000e+00  141.000000
[{'id': 10402, 'name': 'Music'}, {'id': 10749, ...  0.000000e+00  103.000000
[{'id': 10402, 'name': 'Music'}, {'id': 10749, ...  3.680000e+07  157.000000
[{'id': 10402, 'name': 'Music'}, {'id': 10749, ...  0.000000e+00  108.000000