In [3]:
import pandas as pd

In [4]:
col = [
    "sepal_length","sepal_width","petal_length","petal_width",
    "class" 
]
df = pd.read_csv("../../datasets/Iris/Iris.csv", header=None,names=col)

In [11]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
setosa = df[df["class"]=="Iris-setosa"]
versicolor = df[df["class"]=="Iris-versicolor"]

In [7]:
merged = pd.concat([setosa, versicolor])

In [9]:
sorte = merged.sort_values(by='petal_length',ascending=False)

In [10]:
transposed = sorte.T

In [12]:
melted = pd.melt(
    merged,
    id_vars=['class'],
    value_vars=['sepal_length', 'sepal_width','petal_length','petal_width']
)

In [15]:
wide = melted.pivot_table(
    index=['class'],
    columns='variable',
    values='value',
)

In [16]:
merged.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
sorte.head()

    sepal_length  sepal_width  petal_length  petal_width            class
83           6.0          2.7           5.1          1.6  Iris-versicolor
77           6.7          3.0           5.0          1.7  Iris-versicolor
72           6.3          2.5           4.9          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
76           6.8          2.8           4.8          1.4  Iris-versicolor

In [19]:
transposed.head()

,83,77,72,52,76,70,50,56,86,63,...,16,36,38,41,40,42,14,35,13,22
sepal_length,6.0,6.7,6.3,6.9,6.8,5.9,7.0,6.3,6.7,6.1,...,5.4,5.5,4.4,4.5,5.0,4.4,5.8,5.0,4.3,4.6
sepal_width,2.7,3.0,2.5,3.1,2.8,3.2,3.2,3.3,3.1,2.9,...,3.9,3.5,3.0,2.3,3.5,3.2,4.0,3.2,3.0,3.6
petal_length,5.1,5.0,4.9,4.9,4.8,4.8,4.7,4.7,4.7,4.7,...,1.3,1.3,1.3,1.3,1.3,1.3,1.2,1.2,1.1,1.0
petal_width,1.6,1.7,1.5,1.5,1.4,1.8,1.4,1.6,1.5,1.4,...,0.4,0.2,0.2,0.3,0.3,0.2,0.2,0.2,0.1,0.2
class,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,...,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa

In [20]:
melted.head()

         class      variable  value
0  Iris-setosa  sepal_length    5.1
1  Iris-setosa  sepal_length    4.9
2  Iris-setosa  sepal_length    4.7
3  Iris-setosa  sepal_length    4.6
4  Iris-setosa  sepal_length    5.0

In [21]:
wide.head()

variable         petal_length  petal_width  sepal_length  sepal_width
class
Iris-setosa             1.464        0.244         5.006        3.418
Iris-versicolor         4.260        1.326         5.936        2.770