In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("../../datasets/Adult/adult.csv", header=None, names=['age', 'workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','salary'])
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [19]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [20]:
# a. Create data subsets for different Country, Sex, Race
country_subset = df[df["native-country"]==' United-States']
sex_subset = df[df["sex"]==' Male']
race_subset = df[df["race"]==' White']

In [21]:
print("Country Subset (United States):")
print(country_subset.head())
print(f"\nShape: {country_subset.shape}\n")

print("Sex Subset (Male):")
print(sex_subset.head())
print(f"\nShape: {sex_subset.shape}\n")

print("Race Subset (White):")
print(race_subset.head())
print(f"\nShape: {race_subset.shape}")

Country Subset (United States):
   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
5   37            Private  284582     Masters             14

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
5   Married-civ-spouse     Exec-managerial            Wife   White   Female

   capital-gain  capital-loss  hours-per-week  native-country  salary
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
5             0             0              40   United-States   <=50K

Shape: (29153, 15)

Sex Subset (Male):
   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
7   52   Self-emp-not-inc  209642     HS-grad              9

        marital-status          occupation    relationship    race    sex  \
0        Never-married        Adm-clerical   Not-in-family   White   Male
1   Married-civ-spouse     Exec-managerial         Husband   White   Male
2             Divorced   Handlers-cleaners   Not-in-family   White   Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black   Male
7   Married-civ-spouse     Exec-managerial         Husband   White   Male

   capital-gain  capital-loss  hours-per-week  native-country  salary
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
7             0             0              45   United-States    >50K

Shape: (21775, 15)

Race Subset (White):
   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
5   37            Private  284582     Masters             14
7   52   Self-emp-not-inc  209642     HS-grad              9

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
5   Married-civ-spouse     Exec-managerial            Wife   White   Female
7   Married-civ-spouse     Exec-managerial         Husband   White     Male

   capital-gain  capital-loss  hours-per-week  native-country  salary
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
5             0             0              40   United-States   <=50K
7             0             0              45   United-States    >50K

Shape: (27795, 15)

In [22]:
# b. Merge two subsets
merged = pd.concat([sex_subset, race_subset])

In [24]:
# c. Sort Data using relevant numeric column (age)
sorted_data = merged.sort_values(by='age', ascending=False)

In [26]:
# d. Transposing Data
transposed = sorted_data.T

In [28]:
# e. Melting Data to long format
melted = pd.melt(
    merged,
    id_vars=['sex', 'race'],
    value_vars=['age', 'hours-per-week']
)

In [30]:
# f. Casting data to wide format (pivot table)
wide = melted.pivot_table(
    index=['sex'],
    columns='variable',
    values='value',
    aggfunc='mean'
)

In [23]:
print("Merged Data:")
merged.head()

Merged Data:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K

In [25]:
print("Sorted Data (by age):")
sorted_data.head()

Sorted Data (by age):

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
32367,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K
11731,90,?,39824,HS-grad,9,Widowed,?,Not-in-family,White,Male,401,0,4,United-States,<=50K
31030,90,Private,47929,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
11996,90,Private,40388,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,55,United-States,<=50K
18277,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,20,?,<=50K

In [27]:
print("Transposed Data:")
transposed.head()

Transposed Data:

,32367,11731,31030,11996,18277,19747,4070,18725,15356,18832,...,25308,12881,2858,10449,15350,27502,5828,7451,31772,9655
age,90,90,90,90,90,90,90,90,90,90,...,17,17,17,17,17,17,17,17,17,17
workclass,Local-gov,?,Private,Private,Private,Private,Private,Local-gov,Private,Private,...,Private,Private,?,Private,?,Private,Private,Private,?,Private
fnlwgt,214594,39824,47929,40388,311184,226968,313986,153602,90523,115306,...,241185,96282,179715,191910,634226,277583,27032,110798,256173,99161
education,7th-8th,HS-grad,HS-grad,Bachelors,Bachelors,7th-8th,11th,HS-grad,HS-grad,Masters,...,12th,10th,10th,10th,10th,11th,10th,11th,10th,10th
education-num,4,9,9,13,13,4,7,9,9,14,...,8,6,6,6,6,7,6,7,6,6

In [29]:
print("Melted Data (Long Format):")
melted.head()

Melted Data (Long Format):

     sex    race variable  value
0   Male   White      age     39
1   Male   White      age     50
2   Male   White      age     38
3   Male   Black      age     53
4   Male   White      age     52

In [31]:
print("Wide Format Data (Pivot Table):")
wide

Wide Format Data (Pivot Table):

variable        age  hours-per-week
sex
Female    36.819646       36.302676
Male      39.539268       42.541979